name: BRASIL
favicon: null
layout_spectrum: 0.4337282555643469
typography_spectrum: 0.11685984837822616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9574124857317656
  lightness: 0.9083614288829267
  saturation: 0.91688940115273
  rhythmicContrast: 0.693228297168389
purpose: []
